# default wallpapers
wallpaper {
  monitor = 
  path = ~/Pictures/Wallpapers/a_train_crossing_with_a_train_track_and_a_body_of_water.png
  fit_mode = cover
}

splash = false


# fully disable ipc
# ipc = off
